In [2]:
import pandas as pd

df = pd.read_csv("../WEEK1/stock_data.csv")
df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,183.90321350097656,186.6770206585062,182.16958591702465,185.39908100307179,82488700
3,2024-01-03,182.52622985839844,184.1409850600839,181.7138941984477,182.49651173581816,58414500
4,2024-01-04,180.2081298828125,181.37708304150152,179.18776734055538,180.44587486910356,71983600

In [3]:
# If columns are multi-index, flatten them
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
1,Date,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,183.90321350097656,186.6770206585062,182.16958591702465,185.39908100307179,82488700
3,2024-01-03,182.52622985839844,184.1409850600839,181.7138941984477,182.49651173581816,58414500
4,2024-01-04,180.2081298828125,181.37708304150152,179.18776734055538,180.44587486910356,71983600

In [5]:
print(df.columns)
print(df.dtypes)

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')
Price     object
Close     object
High      object
Low       object
Open      object
Volume    object
dtype: object

In [6]:
# Convert price columns to numeric safely
price_cols = ["Open", "High", "Low", "Close", "Volume"]

for col in price_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [7]:
df.dropna(subset=["Close"], inplace=True)

In [8]:
import numpy as np

df["log_return"] = np.log(df["Close"] / df["Close"].shift(1))
df["volatility"] = df["log_return"].rolling(10).std()

df.dropna(inplace=True)
df.head()

,Price,Close,High,Low,Open,Volume,log_return,volatility
12,2024-01-17,180.970917,181.218578,178.613193,179.574120,47317400.0,-0.005187,0.010604
13,2024-01-18,186.865250,187.370473,184.091442,184.349005,78005800.0,0.032051,0.014733
14,2024-01-19,189.767838,190.154188,187.053482,187.558705,68903000.0,0.015414,0.014204
15,2024-01-22,192.076019,193.502549,190.461264,190.500899,60133900.0,0.012090,0.013957
16,2024-01-23,193.353989,193.918663,192.016628,193.195497,42355600.0,0.006631,0.012608

In [9]:
print(df[["Close", "log_return", "volatility"]].head())
print(df.dtypes)

         Close  log_return  volatility
12  180.970917   -0.005187    0.010604
13  186.865250    0.032051    0.014733
14  189.767838    0.015414    0.014204
15  192.076019    0.012090    0.013957
16  193.353989    0.006631    0.012608
Price          object
Close         float64
High          float64
Low           float64
Open          float64
Volume        float64
log_return    float64
volatility    float64
dtype: object