In [50]:
price = pd.read_csv(
    "../WEEK1/stock_data.csv",
    skiprows=[1, 2],
    index_col=0
)

price.index = pd.to_datetime(price.index)
price.index.name = 'date'
price = price.reset_index()

print(price.columns)
print(price['date'].min(), price['date'].max())

Index(['date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')
2024-01-02 00:00:00 2024-12-30 00:00:00

In [51]:
price = pd.read_csv(
    "../WEEK1/stock_data.csv",
    skiprows=[1, 2],
    index_col=0
)

price.index = pd.to_datetime(price.index)
price.index.name = 'date'
price = price.reset_index()

# 🔑 THIS LINE FIXES EVERYTHING
price['date'] = pd.to_datetime(price['date'])

print(price['date'].dtype)
print(sent['date'].dtype)



print(price['date'].dtype)
print(sent['date'].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]

In [52]:
df = pd.merge(price, sent, on='date', how='inner')
print(len(df))
df.head()

3

,date,Close,High,Low,Open,Volume,avg_sentiment
0,2024-01-02,183.903214,186.677021,182.169586,185.399081,82488700,0.929470
1,2024-01-03,182.526230,184.140985,181.713894,182.496512,58414500,-0.952257
2,2024-01-04,180.208130,181.377083,179.187767,180.445875,71983600,-0.347188

In [53]:
# Market features
df['return'] = df['Close'].pct_change()
df['volatility_5d'] = df['return'].rolling(5).std()

# Sentiment lags
df['sentiment_lag1'] = df['avg_sentiment'].shift(1)
df['sentiment_3d'] = df['avg_sentiment'].rolling(3).mean()
df['sentiment_7d'] = df['avg_sentiment'].rolling(7).mean()
print(len(df))
print(df.head(10))

df = df.dropna()
df_clean = df.dropna()
print(len(df_clean))

3
        date       Close        High         Low        Open    Volume  \
0 2024-01-02  183.903214  186.677021  182.169586  185.399081  82488700
1 2024-01-03  182.526230  184.140985  181.713894  182.496512  58414500
2 2024-01-04  180.208130  181.377083  179.187767  180.445875  71983600

   avg_sentiment    return  volatility_5d  sentiment_lag1  sentiment_3d  \
0       0.929470       NaN            NaN             NaN           NaN
1      -0.952257 -0.007488            NaN        0.929470           NaN
2      -0.347188 -0.012700            NaN       -0.952257     -0.123325

   sentiment_7d
0           NaN
1           NaN
2           NaN
0

In [54]:
df.to_csv("WEEK3_dataset.csv", index=False)

df.head()

Empty DataFrame
Columns: [date, Close, High, Low, Open, Volume, avg_sentiment, return, volatility_5d, sentiment_lag1, sentiment_3d, sentiment_7d]
Index: []